-- Add sample tenders and trigger scraper data
INSERT INTO tenders (title, description, organization, category, location, budget_estimate, deadline, status, tender_number, source_url, scraped_from) VALUES
('Road Construction Project - Phase 1', 'Construction of 15km tarmac road connecting rural areas to main highway. Includes drainage systems, road signs, and safety barriers.', 'Kenya Urban Roads Authority (KURA)', 'Infrastructure', 'Kiambu County', 45000000, '2025-02-15', 'active', 'KURA/2025/RD001', 'https://kura.go.ke/tenders', 'KURA Portal'),
('Hospital Equipment Supply', 'Supply and installation of medical equipment including X-ray machines, patient monitors, and laboratory equipment.', 'Ministry of Health', 'Healthcare', 'Nairobi County', 25000000, '2025-01-30', 'active', 'MOH/2025/EQ002', 'https://health.go.ke/tenders', 'MOH Portal'),
('School Infrastructure Development', 'Construction of 20 new classrooms, library, and laboratory for secondary schools in rural areas.', 'Ministry of Education', 'Education', 'Machakos County', 18000000, '2025-02-20', 'active', 'MOE/2025/INFRA003', 'https://education.go.ke/tenders', 'Education Portal'),
('Water Supply System Installation', 'Installation of water supply systems including boreholes, pumps, and distribution networks for 5 villages.', 'Ministry of Water and Sanitation', 'Water & Sanitation', 'Turkana County', 35000000, '2025-03-01', 'active', 'MWS/2025/WS004', 'https://water.go.ke/tenders', 'Water Portal'),
('ICT Infrastructure Upgrade', 'Upgrade of government ICT systems including servers, networking equipment, and cybersecurity solutions.', 'Ministry of ICT', 'Technology', 'Nairobi County', 12000000, '2025-01-25', 'active', 'MICT/2025/ICT005', 'https://ict.go.ke/tenders', 'ICT Portal');

-- Add AI analyses for the inserted tenders
INSERT INTO ai_analyses (tender_id, estimated_value_min, estimated_value_max, win_probability, confidence_score, recommendations, analysis_data, model_version) VALUES
(1, 42000000, 48000000, 75, 85, ARRAY['Highlight experience with similar road projects', 'Include local subcontractors', 'Emphasize quality assurance measures'], '{"competition_level": "medium", "technical_requirements": "high", "financial_capacity_needed": "high"}', 'TenderAI-v1.0'),
(2, 23000000, 27000000, 65, 80, ARRAY['Showcase medical equipment certifications', 'Partner with certified installers', 'Provide comprehensive maintenance plans'], '{"competition_level": "high", "technical_requirements": "very_high", "financial_capacity_needed": "medium"}', 'TenderAI-v1.0'),
(3, 17000000, 19000000, 80, 90, ARRAY['Demonstrate education sector experience', 'Include local community engagement plans', 'Offer extended warranty periods'], '{"competition_level": "low", "technical_requirements": "medium", "financial_capacity_needed": "medium"}', 'TenderAI-v1.0'),
(4, 33000000, 37000000, 70, 78, ARRAY['Show water system expertise', 'Include environmental impact assessments', 'Provide long-term maintenance contracts'], '{"competition_level": "medium", "technical_requirements": "high", "financial_capacity_needed": "high"}', 'TenderAI-v1.0'),
(5, 11500000, 12500000, 85, 88, ARRAY['Highlight cybersecurity expertise', 'Include 24/7 support services', 'Offer training programs for government staff'], '{"competition_level": "low", "technical_requirements": "very_high", "financial_capacity_needed": "low"}', 'TenderAI-v1.0');