-- Create missing tables for RFQ (Request for Quote) workflow and backup systems

-- Table for RFQ (Request for Quote) management
CREATE TABLE public.rfqs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  category character varying NOT NULL,
  budget_range_min bigint,
  budget_range_max bigint,
  deadline date NOT NULL,
  requirements text[] DEFAULT '{}',
  documents text[] DEFAULT '{}',
  location character varying NOT NULL,
  status character varying DEFAULT 'active' CHECK (status IN ('active', 'closed', 'draft', 'awarded')),
  tags text[] DEFAULT '{}',
  preferred_suppliers uuid[] DEFAULT '{}',
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Table for RFQ quotes/proposals from suppliers
CREATE TABLE public.rfq_quotes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rfq_id integer NOT NULL REFERENCES public.rfqs(id) ON DELETE CASCADE,
  supplier_id uuid NOT NULL,
  quoted_amount bigint NOT NULL,
  delivery_timeline character varying,
  proposal_text text,
  attachments text[] DEFAULT '{}',
  validity_period integer DEFAULT 30, -- days
  terms_and_conditions text,
  status character varying DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected', 'withdrawn')),
  submitted_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Table for automatic daily backups tracking
CREATE TABLE public.backup_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  backup_type character varying NOT NULL CHECK (backup_type IN ('database', 'files', 'user_data', 'tenders')),
  backup_location text NOT NULL,
  file_size bigint,
  backup_status character varying DEFAULT 'in_progress' CHECK (backup_status IN ('in_progress', 'completed', 'failed')),
  error_message text,
  checksum character varying,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone
);

-- Table for version control tracking
CREATE TABLE public.version_tracking (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type character varying NOT NULL CHECK (entity_type IN ('tender', 'rfq', 'profile', 'quote', 'consortium')),
  entity_id integer NOT NULL,
  version_number integer NOT NULL DEFAULT 1,
  changes_summary text,
  changed_fields jsonb,
  changed_by uuid,
  change_type character varying CHECK (change_type IN ('create', 'update', 'delete', 'restore')),
  created_at timestamp with time zone DEFAULT now()
);

-- Table for tender analytics and tracking
CREATE TABLE public.tender_analytics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tender_id integer NOT NULL REFERENCES public.tenders(id) ON DELETE CASCADE,
  views_count integer DEFAULT 0,
  saves_count integer DEFAULT 0,
  applications_count integer DEFAULT 0,
  last_viewed timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on all new tables
ALTER TABLE public.rfqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rfq_quotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backup_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.version_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tender_analytics ENABLE ROW LEVEL SECURITY;

-- RLS Policies for RFQs
CREATE POLICY "Users can view all RFQs" ON public.rfqs FOR SELECT USING (true);
CREATE POLICY "Users can create their own RFQs" ON public.rfqs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own RFQs" ON public.rfqs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own RFQs" ON public.rfqs FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for RFQ Quotes
CREATE POLICY "RFQ creators and quote suppliers can view quotes" ON public.rfq_quotes 
FOR SELECT USING (
  auth.uid() = supplier_id OR 
  auth.uid() IN (SELECT user_id FROM public.rfqs WHERE id = rfq_id)
);
CREATE POLICY "Suppliers can create quotes" ON public.rfq_quotes FOR INSERT WITH CHECK (auth.uid() = supplier_id);
CREATE POLICY "Suppliers can update their own quotes" ON public.rfq_quotes FOR UPDATE USING (auth.uid() = supplier_id);
CREATE POLICY "Suppliers can delete their own quotes" ON public.rfq_quotes FOR DELETE USING (auth.uid() = supplier_id);

-- RLS Policies for Backup Logs (admin only)
CREATE POLICY "Admins can manage backup logs" ON public.backup_logs FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies for Version Tracking
CREATE POLICY "Users can view version tracking for their entities" ON public.version_tracking 
FOR SELECT USING (
  CASE entity_type
    WHEN 'tender' THEN true -- All users can see tender versions
    WHEN 'rfq' THEN auth.uid() IN (SELECT user_id FROM public.rfqs WHERE id = entity_id)
    WHEN 'profile' THEN auth.uid()::text = entity_id::text
    WHEN 'quote' THEN auth.uid() IN (SELECT supplier_id FROM public.rfq_quotes WHERE id = entity_id)
    WHEN 'consortium' THEN auth.uid() IN (SELECT created_by FROM public.consortiums WHERE id = entity_id)
    ELSE false
  END
);

-- RLS Policies for Tender Analytics (public read, admin write)
CREATE POLICY "Anyone can view tender analytics" ON public.tender_analytics FOR SELECT USING (true);
CREATE POLICY "Admins can manage tender analytics" ON public.tender_analytics 
FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));

-- Create triggers for updated_at columns
CREATE TRIGGER update_rfqs_updated_at
  BEFORE UPDATE ON public.rfqs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_rfq_quotes_updated_at
  BEFORE UPDATE ON public.rfq_quotes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_tender_analytics_updated_at
  BEFORE UPDATE ON public.tender_analytics
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Create storage buckets for backups and files
INSERT INTO storage.buckets (id, name, public) VALUES 
  ('backups', 'backups', false),
  ('rfq-documents', 'rfq-documents', false),
  ('quote-attachments', 'quote-attachments', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for backup bucket (admin only)
CREATE POLICY "Admins can manage backups" ON storage.objects
FOR ALL USING (bucket_id = 'backups' AND has_role(auth.uid(), 'admin'::app_role));

-- Storage policies for RFQ documents
CREATE POLICY "RFQ creators can upload documents" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'rfq-documents' AND 
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "RFQ creators can view their documents" ON storage.objects
FOR SELECT USING (
  bucket_id = 'rfq-documents' AND 
  auth.uid()::text = (storage.foldername(name))[1]
);

-- Storage policies for quote attachments
CREATE POLICY "Suppliers can upload quote attachments" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'quote-attachments' AND 
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Quote stakeholders can view attachments" ON storage.objects
FOR SELECT USING (
  bucket_id = 'quote-attachments' AND (
    auth.uid()::text = (storage.foldername(name))[1] OR
    auth.uid() IN (
      SELECT rfqs.user_id FROM public.rfqs 
      JOIN public.rfq_quotes ON rfqs.id = rfq_quotes.rfq_id
      WHERE rfq_quotes.supplier_id::text = (storage.foldername(name))[1]
    )
  )
);